### ISSUE TITLE
Get script value for inputs and outputs

### ISSUE THREAD

**Issue by yiwesi** [citp/BlockSci#102]
Hello, it is me again ;)

Suggestion for an enhancement:
Function to get Script value for inputs and outputs.

In this [example](https://api.blockcypher.com/v1/btc/main/txs/0616d01f2f84d43cee37a986d3da6ed3f468e5badf9c0297ebd0e3b67d73b569?limit=50&includeHex=true)

Input[0].script would return: `473044022075ab8c63340f033bc8632cc485c2ae7a3e09448ae08713ee19b0a818432105db02200d717139469263ffc38ee5e4d5db8e3cf2904a81fe72b80260cef3507e985675012103f565ce6581e785d4f0662a714cfee38c6b068b441a0d06c7fe055cfe15408ecb`
and 
Output[0].script would return:
`76a914bdca24e2956bdf1a6bb8fc0387c5c3089742df4488ac`

Or as an alternative a function to get the raw code for a transaction. Then I can extract the script data by myself.

**Comment by hkalodner** [comment]
Hi @yiwesi!

l think this out of scope for what I'm trying to achieve with BlockSci. Rather than storing raw script data, we process the data an extract the important features. Then we surface it through the various `blocksci.Address` [subclasses](https://citp.github.io/BlockSci/reference/addresses/address.html). I think we might store enough data about outputs to recreate the full output script.

Inputs we definitely don't have enough data currently recorded since we don't store signatures. Storing all signatures would run counter to the goal of keeping a handle on the overall size required by BlockSci. I haven't come across any use case where the full signature would be required. I've considered recording the sighash type of each signature, but this would be a somewhat substantial architectural change. Even with that, we'd be losing the exact signature used.

Can I ask what your use case is for this? If it's not just the script data you're trying to get, but some particular information you want to extract from it there might be some other solution.
