### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by waldemarmeier** [citp/BlockSci#107]
When I try parsing the blockchain locally the process does not start. I get following messages

 `blocksci_parser --output-directory /Volumes/JM/parsed_blockchain  update disk --coin-directory  /Volumes/JM`
`Segmentation fault: 11`

Google suggested that it might be a memory issue, but I'm not sure since I installed it locally following the steps described in the set-up guide.

Thanks for your help.

**Comment by hkalodner** [comment]
Hmm. I haven't seen that specific error reported before. How much memory does your machine have and what operating system are you running?

**Comment by waldemarmeier** [comment]
I use a MacBook Pro with 8GB RAM and run macOS 10.13.14

**Comment by hkalodner** [comment]
Sorry, but as we mentioned in the [`setup`](https://citp.github.io/BlockSci/setup.html) section. A minimum of 32 GB of memory is necessary for a local setup of BlockSci. BlockSci's parser is optimized for speed rather than memory which unfortunately means that you need a sufficiently powerful machine to run it.

I use a 16 GB mention to develop and have been able to run it up through 300000, but I think 8GB might be too little to run at all, especially if you don't have much swap space.

**Comment by waldemarmeier** [comment]
I've read the setup guide, but I thought it still might work. Can I tweak the parser somewhere, that it will need less RAM?

thanks for the response.

**Comment by hkalodner** [comment]
Sorry, but I think you're out of luck. Increasing the amount of swap space available might make it possible to run the parser, but it's going to become super slow super quickly and might still crash at some later point.

It would probably be possible to produce a version of the parser that is slower but requires less memory, but unfortunately that's not a very high priority at the moment. BlockSci is developed by mostly just me and I'm mostly currently focused on improving the interface and performance of the frontend rather than the parser.

An alternative to local setup is instead using Amazon EC2 which we provide a ready to use AMI for (Currently out of data running v0.4.5, but soon to be updated).

**Comment by hkalodner** [comment]
The new AMI has been released btw.

**Comment by waldemarmeier** [comment]
I appreciate the support. Maybe I can use BlockSci on the server of my university.
