### ISSUE TITLE
Discrepancies between address types in Bitcoin Core and Blocksci

### ISSUE THREAD

**Issue by satwo** [citp/BlockSci#112]
I've noticed a couple of discrepancies between the address types parsed in Bitcoin Core (https://github.com/bitcoin/bitcoin/blob/master/src/script/standard.cpp) and those in Blocksci (https://citp.github.io/BlockSci/reference/addresses/types.html):

1. The "witness_unknown" type in Bitcoin Core (mostly in place for backwards compatibility for new versions of segwit scripts). Will this be supported in future versions of Blocksci?
2. The "Multisig_Pubkey" address type in Blocksci (distinguished from "plain" Multisig and Pubkey), which doesn't have a direct analogue in Core that I can see. Is there any documentation for this? 

Thanks for the great work on this fantastic project!

**Comment by hkalodner** [comment]
Hi @satwo,

I'm glad you're enjoying using BlockSci. We definitely need to increase the amount of documentation since most of it is just an API reference currently The multisig pubkey type is a special type for describing the pubkey addresses that are components of a multisig address. Bitcoin Core doesn't need any representation of this since it doesn't handle them at all. BlockSci uses them to allow you to find multisig addresses containing a given pubkey.

The "witness_unknown" type is just an oversight. BlockSci should add this. I'll include this in the next data format update. I don't think that existed when I added segwit support initially though I could have just missed it. It's not to big an issue since they're currently just treated as nonstandard addresses and I don't know how many of them there are, but it'd be good to support them.
