### ISSUE TITLE
Error in transaction retrieving for old mining address

### ISSUE THREAD

**Issue by ClementPavue** [citp/BlockSci#187]
I tried to retrieve the transaction of the address which mined block n°546 but I got an empty vector as a result. 
#### Expected Result
According to blockchain.com the address receive 50BTC in one transaction.
#### Actual Result
```
PubkeyHashAddress(13ZZm14ed78RHeEiqHMdLrCTDv928MvZEd)
0
```
#### Reproduction Steps
Here is the code I used.

```
auto address = getAddressFromString("13ZZm14ed78RHeEiqHMdLrCTDv928MvZEd",chain.getAccess()); 
if(address){
  std::cout << (*address).toString() << std::endl;
  std::cout << (*address).getTransactions().size() << std::endl;
}
```
I got the same issue with old mining address but not for recent one. 
Am I doing something wrong here ?

#### System Information
BlockSci version:  0.5 
Using AMI: yes/no no
Total memory: 64GB

**Comment by maltemoeser** [comment]
`getAddressFromString` returns the P2PKH address, but that one has never received any coins. The transaction you're interested in sends the funds to a raw pubkey rather than to a P2PKH script, i.e. they share the same key but are different formats. You'll need to use the EquivAddress to get to the actual PubKey address. E.g., in Python if you don't care about the specific address format:

```python
addr = chain.address_from_string("13ZZm14ed78RHeEiqHMdLrCTDv928MvZEd")
addr.balance()
> 0

equiv_addr = addr.equiv()
equiv_addr.balance()
> 5000000000

**Comment by ClementPavue** [comment]
My bad ! Sorry for the noise.
