### ISSUE TITLE
bitcoin forks other than bitcoin-cash - how to parse them?

### ISSUE THREAD

**Issue by allenday** [citp/BlockSci#196]
I'm specifically interested in: 

- bitcoin gold
- bitcoin diamond
- bitcore
- satoshi's vision
- super smart bitcoin

Do I need to parse these as `custom`, and if not: what is the right procedure?

**Comment by hkalodner** [comment]
I haven't dug too deep into the particulars of each of these. The coin selection in the parser simply fills in chain specific options into the new json configuration files. Depending on how similar or different each coin is from bitcoin, it may be easier to just select bitcoin rather than custom. The disk parser may or may not work depending on what as changed in the fork, for instance bitcoin cash worked out of the box.

The chain specific options are location in `chainparams.cpp` ([Bitcoin](https://github.com/bitcoin/bitcoin/blob/master/src/chainparams.cpp), [Bitcoin Gold](https://github.com/BTCGPU/BTCGPU/blob/master/src/chainparams.cpp), [Bitcoin Diamond](https://github.com/eveybcd/BitcoinDiamond/blob/master/src/chainparams.cpp))

BlockSci uses `base58Prefixes[PUBKEY_ADDRESS]`, `base58Prefixes[SCRIPT_ADDRESS]`, and `bech32_hrp` in order to display addresses correctly and `pchMessageStart` in order for the disk parser to correctly recognize blocks. The directly supported chains have this information automatically filled in whereas other chains require manual setup of the config file.

If the bitcoin fork has made changes that break the parser, it may be difficult to load them into blocksci since the RPC parser is only really performant enough to handle blockchains with significantly less data than Bitcoin.

**Comment by allenday** [comment]
`chainparams.cpp` for [OmniLayer](https://github.com/OmniLayer/omnicore/blob/master/src/chainparams.cpp)

**Comment by hkalodner** [comment]
Since Omni Layer is a layer 2 on top of Bitcoin rather than a fork, there isn't really a separate blockchain to parse for it at the block file level that BlockSci operates on. I was just looking into the protocol last night. I'd be happy to discuss that in #197.
