### ISSUE TITLE
omni layer - how to parse it?

### ISSUE THREAD

**Issue by allenday** [citp/BlockSci#197]
It seems to be the bitcoin chain synchronized by the `omni-core` client, but I want to access the omni layer data instead of the bitcoin data. How can I do this?

I tried and failed as follows:
```
blocksci_parser /data/omni.cfg update

Error while interacting with RPC: std::exception
terminate called after throwing an instance of 'BitcoinException'
  what():  std::exception
```

Here's the config file:
```
{
    "chainConfig": {
        "coinName": "custom",
        "dataDirectory": "/data/omni-parser",
        "pubkeyPrefix": [],
        "scriptPrefix": [],
        "segwitActivationHeight": 0,
        "segwitPrefix": ""
    },
    "parser": {
        "maxBlockNum": -6,
        "rpc": {
            "address": "10.1.1.6",
            "password": "y",
            "port": 3389,
            "username": "x"
        }
    },
    "version": 5
}
```

**Comment by hkalodner** [comment]
Since BlockSci only handles layer 1 parsing, it can't really do much directly with Omni Layer, although it should be totally possible to write code in BlockSci to parse out the Omni related txes.

Using the v0.6 interface you can do some simple data parsing with

```python
omni_addresses = chain.addresses(blocksci.address_type.nulldata).where(lambda opreturn: opreturn.data.startswith(b'omni'))
omni = [x[4:] for x in omni_addresses.data]
version_and_type = [(int.from_bytes(x[:2], byteorder='big'), int.from_bytes(x[2:4], byteorder='big')) for x in omni]
common = Counter(version_and_type).most_common()
```

Which shows that there are 3416671 simple sends.

This method only turns up Omni Layer transactions which use Op return storage so it ignores the pubkey and multig formats which I haven't dug into. It's certainly easy to get all transactions including an output sent to the exodus address using: 
```python
chain.address_from_string("1EXoDusjGwvnjZUyKkxZ4UHEf77z6A5S4P").out_txes.to_list()
```
