### ISSUE TITLE
Request for AMI image in other regions

### ISSUE THREAD

**Issue by joemphilips** [citp/BlockSci#20]
I really want use BlockSci in ap-northeast region in AWS.
Is there any plan to enable AMI image in other regions?
I'm asking this because I couldn't make it work BlockSci on my own instance. And I want to compare with reference ami.

Tell me if there is no plan to do it. Thanks.

**Comment by hkalodner** [comment]
At this point there are no plans to maintain AMI images in multiple regions due to the amount of of effort needed to setup each instance. At some time in the future we might try to do this in order to make it easier to set up in other regions.

If you'd like to set up BlockSci on your own instance, it should hopefully be fairly straightforward using Ubuntu 16.04 and following the build instructions at the bottom of the README. The only thing not included there is the setup instructions for running a Bitcoin full node.

**Comment by joemphilips** [comment]
Thanks for reply. I guess it went something wrong when I first tried to setup, but I will try again and debug by myself if there is no plan to maintain AMI in different region.
