### ISSUE TITLE
cluster_with_address() error: incompatible function arguments

### ISSUE THREAD

**Issue by salber** [citp/BlockSci#218]
In the BlockSci python Demo, 

I am getting an error in the last example,

[Balance held by Cluster]
cluster = cm.cluster_with_address(address)

I get

TypeError: cluster_with_address(): incompatible function arguments. The following argument types are supported:
    1. (self: blocksci.cluster.ClusterManager, address: Address) -> blocksci.cluster.Cluster

Invoked with: <blocksci.cluster.ClusterManager object at 0x7f9bef5e6228>, None

**Comment by maltemoeser** [comment]
Seems to be the same issue as #217?

**Comment by hkalodner** [comment]
As shown on the last line `Invoked with: <blocksci.cluster.ClusterManager object at 0x7f9bef5e6228>, None` the issue is that `address` variable is `None` in your example rather than an `Address` object. Presumably this should not be the case. If you're still having an issue here, please open a new issue given code that should be returning an address, but is instead returning `None`
