### ISSUE TITLE
Questions about cluster size and others

### ISSUE THREAD

**Issue by juqiangl** [citp/BlockSci#220]
Hi,

I built two sets of clustering with and without one-time change heuristics.  With change heuristics, there is one super cluster with 256M+ addresses, then only one more with 100K+ addresses.  Without change heuristics, it looks ok, with 207 clusters of 100K+ addresses, and 1033 clusters with 10+ addresses.  My question is, what went wrong with change heuristics?

Couple of other questions:
- How to tell the max block height with my current database? chain.blocks() didn't work

- With a cluster, I can list size, balances, addresses, how to show its tags?

Thanks,
Jeff

Python code I used to build clustering

import blocksci

chain = blocksci.Blockchain("/data02/blocksci-560k")

change_heuristic = blocksci.heuristics.change.legacy()

no_change_heuristic = blocksci.heuristics.change.legacy() - blocksci.heuristics.change.legacy()

cm1 = blocksci.cluster.ClusterManager.create_clustering("/data02/blocksci-cluster-change", chain, change_heuristic)

cm2 = blocksci.cluster.ClusterManager.create_clustering("/data02/blocksci-cluster-no-change", chain, no_change_heuristic)

#### System Information (if applicable)
BlockSci version: 0.5
Using AMI: yes/no
Total memory: 128G

**Comment by maltemoeser** [comment]
Check out our [FAQ](https://github.com/citp/BlockSci/wiki), it should answer some of your questions!

With clustering in general it can happen that different clusters collapse into each other due to over-eager address linking. This is more likely the more addresses you cluster together (change address clustering combines the cluster of the change address with the cluster of the input addresses). See also [Does BlockSci provide state-of-the-art clustering?](https://github.com/citp/BlockSci/wiki#toc-clustering-overview)

> How to tell the max block height with my current database? chain.blocks() didn't work
```python
len(chain) - 1
# or
chain[-1].height
```
> With a cluster, I can list size, balances, addresses, how to show its tags?

You can use [`tagged_clusters`](https://citp.github.io/BlockSci/reference/clustering/cluster_manager.html#blocksci.cluster.ClusterManager.tagged_clusters) to get an iterator over tagged clusters. However, you need to provide these tags yourself, [BlockSci does not provide tags](https://github.com/citp/BlockSci/wiki#toc-analysis-tagged-addresses).
