### ISSUE TITLE
blocksci_parser - stuck

### ISSUE THREAD

**Issue by pranay01** [citp/BlockSci#26]
I ran the following command with correct coin data directory,

blocksci_parser --coin-directory .bitcoin --output-directory bitcoin-data

But the parser is not giving any output or indications of processing. Also size of bitcoin-data folder is not increasing? How long does the parsing take - and why is it not giving any processing indication?

Also, does blocksci_parser only work if we have complete chain data?

**Comment by shihao-guo** [comment]
if you use `top` or `htop` you will see the cpu and memory use of the process, which gives you some processing indications.

**Comment by pranay01** [comment]
I see blocksci_parser working in htop. But it takes only 0.7% CPU and 228MB memory. I have a system which has a RAM of 6.8 GB. 

When I try to import it in python3.5 , it gives a segmentation fault.
`Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import blocksci
>>> 
>>> chain = blocksci.Blockchain("/mnt/disk1/blocksci_data")
Segmentation fault (core dumped`

**Comment by hkalodner** [comment]
Hi @pranay01,

The segmentation fault is from the python module is likely due to corruption of some sort in the data located at `/mnt/disk1/blocksci_data`. The code is still fairly research quality so it doesn't handle the unexpected very well 😄 

Have you tried the new release of BlockSci that we released yesterday? It should provide feedback through the entire process. If I remember correctly, the previous version didn't provide feedback during the initial block header parsing stage. Now all stages should provide percentage done estimates.

**Comment by Vivism** [comment]
@hkalodner - Is the data set you are using in development publically available?

**Comment by hkalodner** [comment]
I'm not exactly sure what you mean by data set. BlockSci's data is generated directly from raw blockchain data. The readme links to an EC2 AMI which has a BlockSci instance running on it which contains the full Bitcoin blockchain as of a couple days ago. Additionally the data can be generated on any machine running a Bitcoin full node.
