### ISSUE TITLE
Address balance doesn't include mining output

### ISSUE THREAD

**Issue by volak** [citp/BlockSci#29]
```
import blocksci
chain = blocksci.Blockchain("/home/ubuntu/bitcoin/")

// Genesis block's payout address
address = blocksci.Address.from_string("1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa")
address.balance() /1e8
>>> 16.7041087 
```

Balance there should be `66.7041087`

Cool project!

**Comment by volak** [comment]
just found I can do 

`address.script.balance() / 1e8` to get the right balance - if thats the proper way feel free to close

**Comment by hkalodner** [comment]
I'm going to leave this open for now until I decide if there is any way this situation could be improved. The problem is that both P2PK and P2PKH addresses have the same format. The `blocksci.Address.from_string` function currently returns a P2PKH address when passed any address string starting with a '1' since this is the most common case.

The pubkey in question is used in two P2PK outputs and 1130 P2PKH outputs. Calling `address.script.balance()` get's you all 1132 outputs.

This collision between two address types with the same address string format is mainly caused by a historical oddity of Bitcoin so which I don't think has much of a solution. The new pubkey based output type (P2WPKH) has it's own address format.
