### ISSUE TITLE
Questions about clustering

### ISSUE THREAD

**Issue by aingo03304** [citp/BlockSci#354]
I have questions about clustering module.

According to #163 , to implement the dynamic clustering,
I think two of std::unordered_map(<DedupAddress, uint32_t>, <uint32_t, DedupAddress>) can be the solution for this.
However, in the code, addressStarts(scriptStarts) conducts as the bijective mapping in the clustering algorithm. 

Can you explain why you used addressStats for the bijective mapping, and the reason why union-find algorithm you used cannot behave with the DedupAddress object?

And without concurrency (using naive union-find algorithm), is there any obstacle for implementing dynamic clustering method?

**Comment by maltemoeser** [comment]
Since clustering is pretty fast and BlockSci was designed to be used for scientific analysis where you're using a static snapshot of the data, we didn't design the implementation for dynamic updates.

Addresses consist of a type and and index. The index is unique for each type only, not globally. The current implementation simply creates contiguous indexes by appending addresses of different types, it's very easy to compute the contiguous index using the offset of each address type only.
