### ISSUE TITLE
Permissioned/private blockchain support

### ISSUE THREAD

**Issue by RobertDiebels** [citp/BlockSci#4]
Hi everyone,

I just read about BlockSci on [Freedom To Tinker](https://freedom-to-tinker.com/2017/09/11/blocksci-a-platform-for-blockchain-science-and-exploration/ ).
The BlockSci [paper](https://arxiv.org/abs/1709.02489) primarily concerns cryptocurrencies (if I'm not mistaken) and I was wondering whether or not I could use BlockSci to analyse Hyperledger Burrow and Hyperledger Fabric chains.

I'm currently setting up both chains for use in my graduate project. Both Burrow and Fabric expose an RPC API which could possibly be parsed by BlockSci. Or, if adjusting the RPC parser would be simple, in which case I would gladly do a PR with the extended functionality.

If I misunderstood anything please correct.

Greetings, Robert.

**Comment by hkalodner** [comment]
Hi Robert,

I currently haven't done any testing with BlockSci in regards to private blockchains so I'm not sure how easy or difficult this would be. The RPC parser requires the existence of four calls and that their return format includes (but is not limited to) the same fields as Bitcoin:
- getblockcount
- getblockhash
- getblock
- getrawtransaction

I'm not familiar with the details of Hyperledger in regard to their transaction format, but assuming that it follows a similar format as Bitcoin (blocks which include transactions which include inputs and outputs), it should be possible to make it work with BlockSci. Not all blockchains have this format. For instance smart contract platforms like Ethereum use a much different structure and are not supported because data analysis of them requires much different capabilities than analysis of Bitcoin-like cryptocurrencies.

**Comment by RobertDiebels** [comment]
Thanks for the quick reply. I checked Burrow and their RPC API only mentions getblock. I'm not familar with Bitcoin's return format though consider that only 1/4 required calls are present I think it wouldn't be worth checking.

Again thanks for the reply!

**Comment by hkalodner** [comment]
I'm closing this for now since I think this is out of scope of this project as it currently exists.
