### ISSUE TITLE
 Two addresses have the same 'address_num'

### ISSUE THREAD

**Issue by xuegsh** [citp/BlockSci#417]
Please provide a clear and concise description of the problem.
This two addresses have the same 'address_num'. Is this a bug?

print(chain.address_from_string('1Cambiobai1XfTSPtYD4vK32BwYtjH2sYW').address_num)
print(chain.address_from_string('bc1q0ux9dey0ed46kf6hkyrxg9uan767snrth65n0k').address_num)

print result is as follows:
341721162
341721162

#### System Information

Using AMI: no  
BlockSci version: I'm on v0.6 branch, and the commit id is e0237e2f06a19ca81162b7803c599217bc1f3682.
Blockchain: Bitcoin
Parser: Disk
Total memory: 80 GB

**Comment by maltemoeser** [comment]
BlockSci deduplicates addresses of different formats with the same underlying public key. This is the case here:

```python
a = chain.address_from_string('1Cambiobai1XfTSPtYD4vK32BwYtjH2sYW')
a.equiv()
> EquivAddress(PubkeyHashAddress(1Cambiobai1XfTSPtYD4vK32BwYtjH2sYW), WitnessPubkeyAddress(bc1q0ux9dey0ed46kf6hkyrxg9uan767snrth65n0k))

b = chain.address_from_string('bc1q0ux9dey0ed46kf6hkyrxg9uan767snrth65n0k')
b.equiv()
> EquivAddress(PubkeyHashAddress(1Cambiobai1XfTSPtYD4vK32BwYtjH2sYW), WitnessPubkeyAddress(bc1q0ux9dey0ed46kf6hkyrxg9uan767snrth65n0k))
```

You can verify that on blockchain.info too, when spending from [either](https://www.blockchain.com/btc/tx/c23252692806073c748b43bbdd936fb5dea68f9f1371ffc6b58d86a87e232b50) of these [addresses](https://www.blockchain.com/btc/tx/47ae19710f980d632d2dec68d9d9428514a34ef05ae7e4d87a81a1002e9a76c4) the same pubkey is provided (`03c057886e5a60779095ae9b589040f47b5b0d9f25672c91c60a55081b92ba051a`)

**Comment by xuegsh** [comment]
Well, I still have 2 questions:
1. Is 'address_num' the unique identifier of an Address object? If so, the above two addresses should have different 'address_num'.
2. This address '37N1rUBfnKQdAi9TY5RKWRrHqgHdS1jeaG' [using the same pubkey](https://www.blockchain.com/btc/tx/dde8bdd26ab1cb06d584abeb7968c140ac07670724e3c39a5fab6cf35cb927b2) as the above addresses, but its 'address_num' is 98058911.

**Comment by maltemoeser** [comment]
The unique identifier for the addresses is the tuple `(address_num, type)`. Now, from here it get's a bit more complicated under the hood.

Internally, address data is deduplicated for different address types (e.g., pubkeyhash, scripthash). The first two addresses belong to the same deduptype and thus have the same address number.

`37N1rUBfnKQdAi9TY5RKWRrHqgHdS1jeaG` has a different deduptype and thus a different `address_num`. It wraps an address that has the same pubkey as the first two addresses, which is what's called script-equivalence in the [docs](https://citp.github.io/BlockSci/reference/addresses/equiv_address.html).

My example code above didn't correctly reflect that because I ran it on an outdated parsing that didn't have the nesting index correctly built. Basically, if you run `.equiv()` or `.equiv(True)` on any of the three addresses, you should see all three of them being shown as equivalent. If you call `.equiv(False)`, then it will not resolve the script-equivalence.

```python
chain.address_from_string("37N1rUBfnKQdAi9TY5RKWRrHqgHdS1jeaG").equiv()
> EquivAddress(PubkeyHashAddress(1Cambiobai1XfTSPtYD4vK32BwYtjH2sYW), ScriptHashAddress(37N1rUBfnKQdAi9TY5RKWRrHqgHdS1jeaG), WitnessPubkeyAddress(bc1q0ux9dey0ed46kf6hkyrxg9uan767snrth65n0k))
```

**Comment by xuegsh** [comment]
I got it. Thank you.

**Comment by JVfisher** [comment]
I find some addresses which are the same in the Blocksci  but I can't verify that on blockchain.info

like:
addr = chain.address_from_string('35xBGE2nF8aEBxjxMBUBoPJaw5hN43yf68')
> EquivAddress(ScriptHashAddress(35xBGE2nF8aEBxjxMBUBoPJaw5hN43yf68), WitnessPubkeyAddress(bc1qjwcm9ea7f7vmtc3ktak4lpjc0dptu0yerxfq7l))
