### ISSUE TITLE
Slow execution times using AWS setup described in README

### ISSUE THREAD

**Issue by aato** [citp/BlockSci#5]
Just read the paper, thanks for this amazing tool! However I'm getting very slow execution times even though I'm using the same AWS setup as specified in the README:

- ami-1f9b8364
- r4.2xlarge instance
- 8 vCPUs, 61GiB Memory
- 500GiB General Purpose SSD Storage, 1500/3000 IOPS

For example the following line, taken from the example notebook, takes a total of 11 minutes to execute (vs. the 17.5 seconds in the demo notebook): `%time txes = chain.script_type_txes(0, len(chain), blocksci.nulldata)`. It's a fresh instance and I haven't tweaked anything. Any idea what I might be doing wrong?

**Comment by hkalodner** [comment]
Apparently this is because of a [known performance issue](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-initialize.html) in AWS that occurs when starting up an EC2 instance from an existing AMI. When the machine starts up it doesn't actually load all of the data on the disk so that startup can be instant. Instead it only loads the data when it is accessed for the first time. When you run this query a second time, it should hopefully be substantially faster.

Could you try running that line again and reporting back the change in timing? Thanks!

We'll work on methods for minimizing this initial slowdown in the next release.

**Comment by aato** [comment]
Confirmed that running the same query again dramatically reduces run-time:

- 1st run: 38 minutes
- 2nd+ run: 25 seconds

Thanks for the link! I'm going to try running the `fio` command to read all blocks on the device, will report on how long that takes.

**Comment by aato** [comment]
Ran `fio` (took ~12 hours), this issue is now resolved for me; all commands run very quickly. Below is what I did, as per your link:

- Install `fio`: `sudo apt-get install -y fio`
- Determine which block device to run `fio` against. In my case it was `xvda`:
```
ubuntu@ip-XXX-XX-XX-XXX:~$ lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvda    202:0    0  500G  0 disk 
└─xvda1 202:1    0  500G  0 part /
```
- Run `fio`; you may want to run it in the background as it takes ~12 hours: `sudo fio --filename=/dev/xvda --rw=read --bs=128k --iodepth=32 --ioengine=libaio --direct=1 --name=volume-initialize`

**Comment by hkalodner** [comment]
Thanks for exploring this issue! I've added a description of the problem to the readme as well as the solution.
