### ISSUE TITLE
script.revealed_tx throws exception

### ISSUE THREAD

**Issue by dii14** [citp/BlockSci#59]
This is a continuation of #56 
I noticed that sometimes script.revealed_tx throws an index out of bounds exception. I looked through the code and I cannot say I fully understand it so I might be completely wrong, but I think this is normal  because sometimes you just return new Transaction(MAX_INT) and that is why the error is thrown...

**Comment by hkalodner** [comment]
Hmm. Interesting. I'm not exactly sure what's going wrong here, but I'll see if I can recreate the problem on my end. The internal data field has MAX_INT stored in it if the script has never been spent. When calling  script.revealed_tx, it should return None if it stores MAX_INT or a transaction otherwise.

I'll describe how this works in two parts.

1. Parser: This is where all the data is generated. The main class that handles this is AddressWriter(https://github.com/citp/BlockSci/blob/master/src/parser/address_writer.hpp). 

The function,
```
template<blocksci::AddressType::Enum type>
size_t serialize(const ScriptOutput<type> &output, uint32_t txNum)
```
is called on each output on the blockchain. For each new output it serialized a chunk of script data described in https://github.com/citp/BlockSci/blob/master/src/blocksci/scripts/script_data.hpp. The `txFirstSpent` field is initialized to `std::numeric_limits<uint32_t>::max()`.

The function
```
template<blocksci::AddressType::Enum type>
void serialize(const ScriptInput<type> &input, uint32_t txNum, uint32_t outputTxNum)
```
is called on each input. On this first usage of that input, it should update the `txFirstSpent` to be the index of the tx which includes that input.

2. Analysis Library
https://github.com/citp/BlockSci/blob/master/src/blocksci/scripts/script.cpp contains the implementation of the getTransactionRevealed function which is called by script.revealed_tx.  It checks to see whether the script has been spent. If it hasn't been spent it should return None and otherwise should return the Transaction so this should never produce.

The python library is just a thin wrapped over this so it should have the same behavior.

**Comment by hkalodner** [comment]
I've done a bunch of testing an I haven't been able to recreate this issue on my end including rerunning your original query from the previous issue. I think there's a reasonable chance that this issue is gone in the current (updated) version

**Comment by dii14** [comment]
Hmm that must be it. I am using the AMI that u provide so maybe that is not updated to reflect the change.

**Comment by hkalodner** [comment]
We just a released a new version of the AMI this morning running the latest version where everything should be working.

**Comment by dii14** [comment]
Thanks for this. Also brilliant product and very good features! :)

**Comment by hkalodner** [comment]
I'm glad people are finding it useful!
