### ISSUE TITLE
Parallel processing with BlockSci

### ISSUE THREAD

**Issue by mosessoh** [citp/BlockSci#84]
I have noticed that the Address object in BlockSci cannot be pickled.

This results in users not being able to use the multiprocessing libraries which rely on pickling objects.

BlockSci exposes the `map_blocks`, `mapreduce_txes` and `mapreduce_blocks` functions that help us utilise multiple cores to processing the blockchain.

I'm wondering if I am missing something similar for Address objects, as I currently work with lists of Address objects (e.g. to chart the historical balances of an entity's addresses), but not being able to handle this task in a parallel manner has led to quite a slowdown in our research velocity.

This is somewhat related to #83. Thank you very much for your time and work on BlockSci.

**Comment by hkalodner** [comment]
This is an issue in the current release. Native pickle functionality doesn't work on BlockSci objects since they are really pointers into a backing database. This will be fixed in the next release by using a custom Pickler object which takes a reference to the Blockchain that the pickled objects came from. This is already partially implemented in the development branch.
https://github.com/citp/BlockSci/blob/v0.5/Notebooks/blocksci/pickler.py
