### ISSUE TITLE
‘txWithIndex’ is not a member of ‘blocksci::Transaction’

### ISSUE THREAD

**Issue by yiwesi** [citp/BlockSci#96]
I try to get the raw hex values from a transaction. I looked at the example (BlockSci/src/example/example.cpp)
But I get this error:

> gcc -Wall /mnt/s/test.cpp -o test
/mnt/s/test.cpp: In function ‘int main(int, const char**)’:
/mnt/s/test.cpp:16:32: error: ‘txWithIndex’ is not a member of ‘blocksci::Transaction’
         auto tx = Transaction::txWithIndex(191057263);

What am I doing wrong?

Code:
> #include <blocksci/blocksci.hpp>
#include <blocksci/chain/transaction.hpp>
#include <blocksci/chain/block.hpp>
#include <blocksci/chain/transaction_range.hpp>
>
> #include <iostream>
>
> using namespace blocksci;
>
> int main(int argc, const char * argv[]) {
        blocksci::Blockchain chain{"/mnt/s/BlockSci"};        
        auto tx = Transaction::txWithIndex(191057263);
        std::cout << tx.getHash().GetHex() << "\n";
}

Sorry for possible Noob Question. I'm not very familiar with C++.

**Comment by hkalodner** [comment]
I'm sorry the C++ code isn't really at all documented currently since I've been focusing on the python interface so it's pretty reasonable to be confused by it. I need to clear out example.cpp since it's mostly out of date. The current method for doing this is 

`Transaction(191057263, chain.getAccess());`
